import placeholders from "@/data/placeholders.json";

/**
 * Image quality tiers (must be listed in next.config `images.qualities`).
 * Full-bleed hero banners get more detail; tiles and cards use the default.
 */
export const QUALITY = { hero: 85, tile: 75 } as const;

/**
 * Blurred 10px preview for a public image (generated by
 * scripts/prepare-assets.py), so a tile shows the photo's colours
 * immediately instead of an empty box while the real file loads.
 */
export function blurProps(src: string): { placeholder: "blur"; blurDataURL: string } | { placeholder: "empty" } {
  const data = (placeholders as Record<string, string>)[src];
  return data ? { placeholder: "blur", blurDataURL: data } : { placeholder: "empty" };
}
