import type { Metadata, Viewport } from "next";
import { brandFont } from "./fonts";
import { shareMetadata, siteDescription, siteUrl } from "@/lib/seo";

// Theme stylesheets, in the same order the original page loaded them.
import "@/styles/theme/base.css";
import "@/styles/theme/global-blocks.css";
import "@/styles/theme/component-product_card.css";
import "@/styles/theme/component-selectbox.css";
import "@/styles/theme/component-swiper.css";
import "@/styles/theme/desktop-menu.css";
import "@/styles/theme/component-popup.css";
import "@/styles/theme/section-sidebar_menu.css";
import "@/styles/theme/cart.css";
import "@/styles/theme/section-sidebar_cart.css";
import "@/styles/theme/component-search.css";
import "@/styles/theme/section-collection-showcase.css";
import "@/styles/theme/section-heading_text.css";
import "@/styles/theme/section-custom-image-gallery.css";
import "@/styles/theme/section-product_carousel.css";
import "@/styles/theme/section-lookbook.css";
import "@/styles/theme/main-footer.css";
import "@/styles/theme/inline.css";
// Base UI component animations — must follow the theme CSS it overrides.
import "@/styles/base-ui.css";
import "@/styles/transitions.css";

import { UIProvider } from "@/components/UIProvider";
import { CartProvider } from "@/components/cart/CartProvider";
import { AnnouncementBar } from "@/components/AnnouncementBar";
import { Header } from "@/components/Header/Header";
import { MobileMenu } from "@/components/Header/MobileMenu";
import { CartDrawer, CountryDrawer, SearchDrawer } from "@/components/drawers/Drawers";
import { Footer } from "@/components/Footer/Footer";
import { ScrollReveal } from "@/components/ScrollReveal";
import { SmoothScroll } from "@/components/SmoothScroll";
import { Cursor } from "@/components/ui/Cursor";

// Icons (favicon.ico, icon.png, apple-icon.png) and share images
// (opengraph-image.jpg, twitter-image.jpg) are file conventions in src/app,
// generated by scripts/prepare-assets.py.
export const metadata: Metadata = {
  metadataBase: siteUrl,
  title: {
    default: "Maliha by Anar & Anoli | Handcrafted Occasion Wear",
    template: "%s | Maliha",
  },
  description: siteDescription,
  applicationName: "Maliha",
  keywords: ["Maliha", "Anar & Anoli", "Indian occasion wear", "kurta sets", "sharara", "lehenga", "dupatta", "womenswear"],
  ...shareMetadata({
    title: "Maliha by Anar & Anoli | Handcrafted Occasion Wear",
    description: siteDescription,
    path: "/",
  }),
};

export const viewport: Viewport = {
  themeColor: "#fdfcfb",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`js ${brandFont.variable}`}>
      <body>
        <a className="skipToContent u-p4" href="#MainContent">
          {" "}
          Skip to content{" "}
        </a>
        <SmoothScroll />
        <Cursor />
        <UIProvider>
          <CartProvider>
          {/* Empty first grid row, like the original newsletter-popup section. */}
          <div className="shopify-section" />
          <AnnouncementBar />
          <Header />
          <MobileMenu />
          <CartDrawer />
          <SearchDrawer />
          {children}
          <Footer />
          <CountryDrawer />
          <ScrollReveal />
          </CartProvider>
        </UIProvider>
      </body>
    </html>
  );
}
